#!/bin/bash

choice=$(cliphist list | wmenu "$@" -l 15 -p "Clipboard>")
[ -z "$choice" ] && exit 0

printf '%s' "$choice" | cliphist decode | wl-copy

notify-send -a clipboard 'Clipboard' 'Item copied'
