#!/bin/sh
CONF="vpn"

if ip link show "$CONF" >/dev/null 2>&1; then
    sudo -n wg-quick down "$CONF"
    notify-send -i network-vpn-disconnected "VPN" "Disconnected"
else
    err=$(sudo -n wg-quick up "$CONF" 2>&1) \
        && notify-send -i network-vpn "VPN" "Connected" \
        || notify-send -u critical "VPN" "Connection failed:
$err"
fi
